[frontend]
32.195.64.175 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-project-key.pem

[backend]
32.196.130.219 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-project-key.pem private_ip=10.0.1.143

[worker]
13.222.104.74 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-project-key.pem

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'